title: Brunhilde

services:
    - 
        type: PackageInformation
        platform: Mac
    - 
        type: PackageInformation
        platform: Win32
    - 
        type: Deployment
        platform: Mac
    - 
        type: Deployment
        platform: Win32