---
:title: Fafnir
:services:
-   :type: ComputerInformation
    :platform: Win32
    :variables: 
        :computer_key_field: :serial_number
-   :type: SoftwareManagement
    :platform: Win32
    :variables: 
        :computer_key_field: :serial_number
-   :type: PackageInformation
    :platform: Win32